const Ziggy = {
  url: "http:\/\/localhost",
  port: null,
  defaults: {},
  routes: {
    login: { uri: "auth\/login", methods: ["GET", "HEAD"] },
    register: { uri: "member\/registration", methods: ["GET", "HEAD"] },
    dashboard: { uri: "dashboard", methods: ["GET", "HEAD"] },
    logout: { uri: "dashboard\/auth\/logout", methods: ["POST"] },
    "profile.update": { uri: "dashboard\/profile", methods: ["PUT"] },
    "list-member.index": { uri: "dashboard\/list-member", methods: ["GET", "HEAD"] },
    "list-member.batches.store": { uri: "dashboard\/list-member\/batches", methods: ["POST"] },
    "list-member.batches.update": {
      uri: "dashboard\/list-member\/batches\/{batch}",
      methods: ["PUT"],
      parameters: ["batch"],
      bindings: { batch: "id" },
    },
    "list-member.batches.destroy": {
      uri: "dashboard\/list-member\/batches\/{batch}",
      methods: ["DELETE"],
      parameters: ["batch"],
      bindings: { batch: "id" },
    },
    "list-member.members.store": { uri: "dashboard\/list-member\/members", methods: ["POST"] },
    "list-member.members.update": {
      uri: "dashboard\/list-member\/members\/{batchMember}",
      methods: ["PUT"],
      parameters: ["batchMember"],
      bindings: { batchMember: "id" },
    },
    "list-member.members.destroy": {
      uri: "dashboard\/list-member\/members\/{batchMember}",
      methods: ["DELETE"],
      parameters: ["batchMember"],
      bindings: { batchMember: "id" },
    },
    "gallery.index": { uri: "dashboard\/gallery", methods: ["GET", "HEAD"] },
    "gallery.store": { uri: "dashboard\/gallery", methods: ["POST"] },
    "gallery.update": {
      uri: "dashboard\/gallery\/{gallery}",
      methods: ["PUT", "PATCH"],
      parameters: ["gallery"],
      bindings: { gallery: "id" },
    },
    "gallery.destroy": {
      uri: "dashboard\/gallery\/{gallery}",
      methods: ["DELETE"],
      parameters: ["gallery"],
      bindings: { gallery: "id" },
    },
    "news.index": { uri: "dashboard\/news", methods: ["GET", "HEAD"] },
    "news.create": { uri: "dashboard\/news\/create", methods: ["GET", "HEAD"] },
    "news.store": { uri: "dashboard\/news", methods: ["POST"] },
    "news.edit": {
      uri: "dashboard\/news\/{news}\/edit",
      methods: ["GET", "HEAD"],
      parameters: ["news"],
      bindings: { news: "id" },
    },
    "news.update": {
      uri: "dashboard\/news\/{news}",
      methods: ["PUT", "PATCH"],
      parameters: ["news"],
      bindings: { news: "id" },
    },
    "news.destroy": {
      uri: "dashboard\/news\/{news}",
      methods: ["DELETE"],
      parameters: ["news"],
      bindings: { news: "id" },
    },
    "events.index": { uri: "dashboard\/events", methods: ["GET", "HEAD"] },
    "events.store": { uri: "dashboard\/events", methods: ["POST"] },
    "events.update": {
      uri: "dashboard\/events\/{event}",
      methods: ["PUT"],
      parameters: ["event"],
      bindings: { event: "id" },
    },
    "events.destroy": {
      uri: "dashboard\/events\/{event}",
      methods: ["DELETE"],
      parameters: ["event"],
      bindings: { event: "id" },
    },
    "orders.store": { uri: "dashboard\/orders", methods: ["POST"] },
    "orders.update-status": {
      uri: "dashboard\/orders\/{order}\/status",
      methods: ["PUT"],
      parameters: ["order"],
      bindings: { order: "id" },
    },
    "orders.destroy": {
      uri: "dashboard\/orders\/{order}",
      methods: ["DELETE"],
      parameters: ["order"],
      bindings: { order: "id" },
    },
    "accounts.store": { uri: "dashboard\/accounts", methods: ["POST"] },
    "accounts.update": {
      uri: "dashboard\/accounts\/{account}",
      methods: ["PUT"],
      parameters: ["account"],
      bindings: { account: "id" },
    },
    "accounts.destroy": {
      uri: "dashboard\/accounts\/{account}",
      methods: ["DELETE"],
      parameters: ["account"],
      bindings: { account: "id" },
    },
    web: {
      uri: "{any?}",
      methods: ["GET", "HEAD"],
      wheres: { any: "^(?!auth|admin|api|dashboard|sitemap\\.xml).*$" },
      parameters: ["any"],
    },
    "storage.local": {
      uri: "storage\/{path}",
      methods: ["GET", "HEAD"],
      wheres: { path: ".*" },
      parameters: ["path"],
    },
    "storage.local.upload": {
      uri: "storage\/{path}",
      methods: ["PUT"],
      wheres: { path: ".*" },
      parameters: ["path"],
    },
  },
};
if (typeof window !== "undefined" && typeof window.Ziggy !== "undefined") {
  Object.assign(Ziggy.routes, window.Ziggy.routes);
}
export { Ziggy };
