import profile from "@/assets/gallery-2.jpg";

export const useMembers = () => {
  const names = [
    "Asep Saepuloh",
    "Rizky Ramadhan",
    "Siti Nurhaliza",
    "Budi Santoso",
    "Dewi Anggraini",
    "Fajar Nugraha",
    "Indah Permata",
    "Muhammad Farhan",
    "Nabila Putri",
    "Rian Hidayat",
    "Agus Wijaya",
    "Dian Sastro",
    "Eko Prasetyo",
    "Fitriani",
    "Gilang Pratama",
    "Hendra Kurniawan",
    "Intan Lestari",
    "Joko Susilo",
    "Kurnia Dewi",
    "Lutfi Hakim",
    "Mega Utami",
    "Naufal Abdi",
    "Okta Rama",
    "Putri Maharani",
    "Qori Sanjaya",
    "Reza Rahadian",
    "Sari Utami",
    "Taufik Hidayat",
    "Utami Kusuma",
    "Vina Panduwinata",
  ];

  const prodis = [
    "Administrasi Bisnis",
    "Teknik Informatika",
    "Sistem Informasi",
    "Manajemen",
    "Akuntansi",
    "Ilmu Komunikasi",
    "Desain Komunikasi Visual",
    "Teknik Industri",
    "Sastra Sunda",
    "Pendidikan Musik",
  ];

  // Helper function untuk mengambil item acak dari array
  const getRandom = (arr: string[]) => arr[Math.floor(Math.random() * arr.length)];

  return [
    {
      id: 1,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2022",
      batch_name: "Angkatan Asmarandana",
      status: "Aktif",
    },
    {
      id: 2,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2022",
      batch_name: "Angkatan Asmarandana",
      status: "Aktif",
    },
    {
      id: 3,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2022",
      batch_name: "Angkatan Asmarandana",
      status: "Aktif",
    },
    {
      id: 4,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2022",
      batch_name: "Angkatan Asmarandana",
      status: "Aktif",
    },
    {
      id: 5,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2022",
      batch_name: "Angkatan Asmarandana",
      status: "Aktif",
    },
    {
      id: 6,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2022",
      batch_name: "Angkatan Asmarandana",
      status: "Aktif",
    },
    {
      id: 7,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2022",
      batch_name: "Angkatan Asmarandana",
      status: "Aktif",
    },
    {
      id: 8,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2022",
      batch_name: "Angkatan Asmarandana",
      status: "Aktif",
    },
    {
      id: 9,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2022",
      batch_name: "Angkatan Asmarandana",
      status: "Aktif",
    },
    {
      id: 10,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2022",
      batch_name: "Angkatan Asmarandana",
      status: "Aktif",
    },
    {
      id: 11,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2022",
      batch_name: "Angkatan Asmarandana",
      status: "Aktif",
    },
    {
      id: 12,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2022",
      batch_name: "Angkatan Asmarandana",
      status: "Aktif",
    },
    {
      id: 13,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2022",
      batch_name: "Angkatan Asmarandana",
      status: "Aktif",
    },
    {
      id: 14,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2022",
      batch_name: "Angkatan Asmarandana",
      status: "Aktif",
    },
    {
      id: 15,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2022",
      batch_name: "Angkatan Asmarandana",
      status: "Aktif",
    },
    {
      id: 16,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2021",
      batch_name: "Angkatan Pranata",
      status: "Non-Aktif",
    },
    {
      id: 17,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2021",
      batch_name: "Angkatan Pranata",
      status: "Non-Aktif",
    },
    {
      id: 18,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2021",
      batch_name: "Angkatan Pranata",
      status: "Non-Aktif",
    },
    {
      id: 19,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2021",
      batch_name: "Angkatan Pranata",
      status: "Non-Aktif",
    },
    {
      id: 20,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2021",
      batch_name: "Angkatan Pranata",
      status: "Non-Aktif",
    },
    {
      id: 21,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2021",
      batch_name: "Angkatan Pranata",
      status: "Non-Aktif",
    },
    {
      id: 22,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2021",
      batch_name: "Angkatan Pranata",
      status: "Non-Aktif",
    },
    {
      id: 23,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2021",
      batch_name: "Angkatan Pranata",
      status: "Non-Aktif",
    },
    {
      id: 24,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2021",
      batch_name: "Angkatan Pranata",
      status: "Non-Aktif",
    },
    {
      id: 25,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2021",
      batch_name: "Angkatan Pranata",
      status: "Non-Aktif",
    },
    {
      id: 26,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2021",
      batch_name: "Angkatan Pranata",
      status: "Non-Aktif",
    },
    {
      id: 27,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2021",
      batch_name: "Angkatan Pranata",
      status: "Non-Aktif",
    },
    {
      id: 28,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2021",
      batch_name: "Angkatan Pranata",
      status: "Non-Aktif",
    },
    {
      id: 29,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2021",
      batch_name: "Angkatan Pranata",
      status: "Non-Aktif",
    },
    {
      id: 30,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2021",
      batch_name: "Angkatan Pranata",
      status: "Non-Aktif",
    },
    {
      id: 31,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2020",
      batch_name: "Angkatan Angkasa",
      status: "Non-Aktif",
    },
    {
      id: 32,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2020",
      batch_name: "Angkatan Angkasa",
      status: "Non-Aktif",
    },
    {
      id: 33,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2020",
      batch_name: "Angkatan Angkasa",
      status: "Non-Aktif",
    },
    {
      id: 34,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2020",
      batch_name: "Angkatan Angkasa",
      status: "Non-Aktif",
    },
    {
      id: 35,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2020",
      batch_name: "Angkatan Angkasa",
      status: "Non-Aktif",
    },
    {
      id: 36,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2020",
      batch_name: "Angkatan Angkasa",
      status: "Non-Aktif",
    },
    {
      id: 37,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2020",
      batch_name: "Angkatan Angkasa",
      status: "Non-Aktif",
    },
    {
      id: 38,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2020",
      batch_name: "Angkatan Angkasa",
      status: "Non-Aktif",
    },
    {
      id: 39,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2020",
      batch_name: "Angkatan Angkasa",
      status: "Non-Aktif",
    },
    {
      id: 40,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2020",
      batch_name: "Angkatan Angkasa",
      status: "Non-Aktif",
    },
    {
      id: 41,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2020",
      batch_name: "Angkatan Angkasa",
      status: "Non-Aktif",
    },
    {
      id: 42,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2020",
      batch_name: "Angkatan Angkasa",
      status: "Non-Aktif",
    },
    {
      id: 43,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2020",
      batch_name: "Angkatan Angkasa",
      status: "Non-Aktif",
    },
    {
      id: 44,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2020",
      batch_name: "Angkatan Angkasa",
      status: "Non-Aktif",
    },
    {
      id: 45,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2020",
      batch_name: "Angkatan Angkasa",
      status: "Non-Aktif",
    },
    {
      id: 46,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2020",
      batch_name: "Angkatan Angkasa",
      status: "Non-Aktif",
    },
    {
      id: 47,
      name: getRandom(names),
      img: profile,
      prodi: getRandom(prodis),
      position: "Ketua Umum",
      batch: "2020",
      batch_name: "Angkatan Angkasa",
      status: "Non-Aktif",
    },
  ];
};